---

- name: Look Up Existing EC2 Instances
  local_action:
    module: ec2_lookup
    region: "{{ region }}"
    tags: "{{ instance_tags }}"
  register: ec2_pre_launch

- name: calculate number of instances to provision
  set_fact: 
    count: "{{ num_instances - ec2_pre_launch.instances|length }}"

- name: Launch EC2 Instance
  when: count > 0
  local_action:
    module: ec2
    keypair: "{{ keypair }}"
    group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: yes
    wait: true
    region: "{{ region }}"
    instance_tags: "{{instance_tags}}"
    volumes:
      - snapshot: "{{ snapshot }}"
        device_name: /dev/xvda
        volume_size: "{{ root_ebs_size }}"
    zone: "{{ zone }}"
    count: "{{ count }}"
  register: ec2

- name: Wait for SSH to Come Up
  when: count > 0
  local_action:
    module: wait_for
    host: "{{ item.public_dns_name }}"
    state: started
    port: 22
    delay: 60
    timeout: 600
  with_items: ec2.instances

- name: Gather All EC2 Instances
  local_action:
    module: ec2_lookup
    region: "{{ region }}"
    tags: "{{ instance_tags }}"
  register: ec2_post_launch

- name: Add new instance to host group
  local_action:
    module: add_host
    hostname: "{{ item.public_dns_name }}"
    groupname: launched
  with_items: ec2_post_launch.instances

- name: create alarm
  ec2_metric_alarm:
    state: present
    region: "{{ region }}"
    name: "cpu-high"
    metric: "CPUUtilization"
    namespace: "AWS/EC2"
    statistic: Average
    comparison: ">="
    threshold: 50.0
    period: 300
    evaluation_periods: 1
    unit: "Percent"
    description: "Alarm when average CPU usage is over 50% for more than 5 minutes"
    dimensions: {'InstanceId':'{{ item.id }}'}
    alarm_actions: ["arn:aws:sns:us-west-2:038334053037:leviathan_demo"]
  with_items: ec2_post_launch.instances

- name: debug
  debug: var=tag_Name_leviathan-ansible-built
