---

- name: Update packages
  remote_user: "{{ aws_user }}"
  sudo: yes
  yum: name=* update_cache=yes state=latest

- name: Install LAMP packages
  remote_user: "{{ aws_user }}"
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
    - httpd24
    - php56
    - mysql55-server
    - php56-mysqlnd
    - gcc
    - python-devel
    - mysql-devel
    - stress

- name: Install Python packages
  remote_user: "{{ aws_user }}"
  sudo: yes
  pip: name=MySQL-python state=present

- name: Start Apache web server
  remote_user: "{{ aws_user }}"
  sudo: yes
  service: name=httpd state=restarted

- name: Apache restarts on server reboot
  remote_user: "{{ aws_user }}"
  sudo: yes
  action: command /sbin/chkconfig httpd on

- name: Create www group
  sudo: yes
  group: name=www state=present

- name: Assign default user to www group
  sudo: yes
  user:
    name: "{{ aws_user }}"
    groups: www
    append: yes

- name: Set permission
  remote_user: "{{ aws_user }}"
  sudo: yes
  file: path=/var/www/html owner="{{ aws_user }}" group=www mode=2775 force=yes state=directory
  notify:
    - restart apache

- name: Install default index.php
  remote_user: "{{ aws_user }}"
  sudo: yes
  copy:
    src: www/
    dest: /var/www/html
