---

- name: Start the MySQL service
  sudo: yes
  service:
    name: mysqld
    state: started
    enabled: true

- name: Get DB Password
  include_vars: secrets.yml

- name: update mysql root password for all root accounts
  sudo: yes
  sudo_user: root
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ DB_PASSWORD }}"
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy user my.cnf file with root password credentials
  sudo: yes
  sudo_user: root
  template:
    src: "my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: "root"
    group: "root"
    mode: 0600

- name: remove MySQL test database
  sudo: yes
  sudo_user: root
  mysql_db:
    name: test
    state: absent

- name: create default MySQL db
  sudo: yes
  sudo_user: root
  mysql_db:
    name: leviathan_demo
    state: present
