---

- name: Install System Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  sudo: yes
  with_items:
    - gdal-bin
    - imagemagick

- name: Clone landsat Repository
  sudo: yes
  sudo_user: landsatawsuser
  git: repo=https://github.com/recombinators/worker.git dest={{ snapsat_home }} force=yes version=master

- name: Install Python Dependencies
  sudo: yes
  pip:
    state: present
    requirements: "{{ snapsat_home }}/requirements.txt"

- name: Create Download Directory
  sudo: yes
  sudo_user: landsatawsuser
  file: path={{ snapsat_home }}/download state=directory

- name: Get DB Password url and email env variables
  include_vars: secrets.yml

- name: Set DB URL
  set_fact: 
    db_url: "{{ DATABASE_URL }}"
